AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: alegra-challenge-api

Parameters:
  GoogleApiKey:
    Type: String
  GoogleApiCx:
    Type: String

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        GOOGLE_API_KEY: !Ref GoogleApiKey
        GOOGLE_API_CX: !Ref GoogleApiCx

Resources:
  QueryImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/Images/functions/queryImages/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /query-images
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
