AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: alegra-challenge-api

Parameters:
  GoogleApiKey:
    Type: String
  GoogleApiCx:
    Type: String
  AlegraApiUsername:
    Type: String
  AlegraApiPassword:
    Type: String

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        GOOGLE_API_KEY: !Ref GoogleApiKey
        GOOGLE_API_CX: !Ref GoogleApiCx
        ALEGRA_API_USERNAME: !Ref AlegraApiUsername
        ALEGRA_API_PASSWORD: !Ref AlegraApiPassword

Resources:
  QueryImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/Images/functions/queryImages/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        QueryImages:
          Type: Api
          Properties:
            Path: /query-images
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  GetGameSellersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/Sellers/functions/getGameSellers/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        QueryImages:
          Type: Api
          Properties:
            Path: /get-game-sellers
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
