AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: alegra-challenge-api

Metadata: &esbuild
  BuildMethod: esbuild
  BuildProperties:
    Minify: true
    Target: es2020
    Sourcemap: true
    EntryPoints:
      - app.ts

Parameters:
  GoogleApiKey:
    Type: String
  GoogleApiCx:
    Type: String
  AlegraApiUsername:
    Type: String
  AlegraApiPassword:
    Type: String

Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''content-type'''
      AllowOrigin: '''*'''
  Function:
    Timeout: 12
    Runtime: nodejs20.x
    Handler: app.lambdaHandler
    Architectures:
      - x86_64
    Environment:
      Variables:
        GOOGLE_API_KEY: !Ref GoogleApiKey
        GOOGLE_API_CX: !Ref GoogleApiCx
        ALEGRA_API_USERNAME: !Ref AlegraApiUsername
        ALEGRA_API_PASSWORD: !Ref AlegraApiPassword

Resources:
  QueryImagesFunction:
    Type: AWS::Serverless::Function
    Metadata: *esbuild
    Properties:
      CodeUri: modules/Images/functions/queryImages/
      Events:
        QueryImages:
          Type: Api
          Properties:
            Path: /query-images
            Method: get

  GetGameSellersFunction:
    Type: AWS::Serverless::Function
    Metadata: *esbuild
    Properties:
      CodeUri: modules/Sellers/functions/getGameSellers/
      Events:
        GetGameSellers:
          Type: Api
          Properties:
            Path: /get-game-sellers
            Method: get

  CreateInvoiceFunction:
    Type: AWS::Serverless::Function
    Metadata: *esbuild
    Properties:
      CodeUri: modules/Invoices/functions/createInvoice/
      Events:
        CrateInvoice:
          Type: Api
          Properties:
            Path: /create-invoice
            Method: post
